-- V1: esquema inicial de Torii.
--
-- Las migraciones de Flyway son INMUTABLES una vez aplicadas: si mañana hay que
-- cambiar algo, se crea V2__lo_que_sea.sql — nunca se edita esta. Flyway lleva la
-- cuenta de qué versión tiene cada base de datos (tabla flyway_schema_history).
--
-- El SQL es estándar a propósito: se aplica igual en PostgreSQL (Supabase) y en la
-- H2 en modo PostgreSQL que usan los tests.

-- Usuarios y su plan. La autenticación llegará en una fase posterior; la tabla
-- existe desde ya para que searches pueda referenciarla.
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    name          VARCHAR(120) NOT NULL,
    plan          VARCHAR(20)  NOT NULL DEFAULT 'FREE',
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Historial de búsquedas. user_id es NULLABLE a propósito: hasta que haya
-- autenticación, las búsquedas se guardan como anónimas.
CREATE TABLE searches (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT REFERENCES users (id),
    origin           VARCHAR(3)  NOT NULL,
    destination      VARCHAR(3)  NOT NULL,
    range_start      DATE        NOT NULL,
    range_end        DATE        NOT NULL,
    base_duration    INT         NOT NULL,
    variability      INT         NOT NULL,
    search_precision VARCHAR(20) NOT NULL,
    max_stops        INT         NOT NULL,
    top_n            INT         NOT NULL,
    max_price        NUMERIC(10, 2),
    queries_used     INT         NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_searches_user_created ON searches (user_id, created_at);

-- Mejor precio OBSERVADO cada día para una ruta. Lo alimenta cada búsqueda real
-- (las ofertas del MockFlightProvider se excluyen) y lo consume el gráfico de
-- histórico del frontend. Una fila por (ruta, día): si el mismo día aparece un
-- precio mejor, se actualiza la fila.
-- OJO: "day" y "month" son palabras reservadas en H2 (la BD de los tests), por
-- eso las columnas de fecha llevan nombres más explícitos.
CREATE TABLE price_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin      VARCHAR(3)     NOT NULL,
    destination VARCHAR(3)     NOT NULL,
    observed_on DATE           NOT NULL,
    best_price  NUMERIC(10, 2) NOT NULL,
    currency    VARCHAR(3)     NOT NULL,
    provider    VARCHAR(60),
    CONSTRAINT uq_price_history_route_day UNIQUE (origin, destination, observed_on)
);

-- Consultas consumidas por usuario y mes, para aplicar los límites de cada plan
-- (fase de planes/cuotas). month = primer día del mes.
CREATE TABLE plan_usage (
    user_id      BIGINT NOT NULL REFERENCES users (id),
    usage_month  DATE   NOT NULL,
    queries_used INT    NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, usage_month)
);
