-- V3: password reset and email verification.
--
-- email_verified starts FALSE for everyone, existing accounts included: they get the
-- "confirm your email" notice and can confirm it with one click.
-- password_changed_at lets the API reject JWTs issued before the last password
-- change, so a reset also logs out any other open session.
-- One statement per column, same reason as V2 (PostgreSQL and H2 both accept it).
ALTER TABLE users ADD COLUMN email_verified BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE users ADD COLUMN password_changed_at TIMESTAMP WITH TIME ZONE;

-- Single-use links sent by email. Only the SHA-256 of the token is stored: a leaked
-- table doesn't give anyone a working link.
CREATE TABLE auth_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    purpose     VARCHAR(30) NOT NULL,
    token_hash  VARCHAR(64) NOT NULL UNIQUE,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at     TIMESTAMP WITH TIME ZONE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_auth_tokens_user_purpose ON auth_tokens (user_id, purpose, created_at);
